#!/bin/bash

function launchbar() {
    killall -q polybar # Terminate already running bar instances
    while pgrep -x polybar >/dev/null; do sleep 1; done # Wait until the processes have been shut down
    case "$1" in
        full)
            for m in $(xrandr --query | grep " connected" | cut -d" " -f1);
            do
                MONITOR=$m polybar lap -q &
                MONITOR=$m polybar schedule -q &
            done
            ;;
        mini)
            for m in $(xrandr --query | grep " connected" | cut -d" " -f1);
            do
                MONITOR=$m polybar minimal -q &
            done
            ;;
        none)
            sleep 1
            ;;
        *)
            echo "usage $0 {full|mini|none}"
            exit 1
            ;;
    esac
}

function main() {
    if [ -z "$1" ]; then #are args given
        launchbar "$(head -1 ~/.config/.bartoggle)"
    else
        launchbar"$1"
    fi
}

main "$1"
